# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "nvisy-core"
version = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = "./README.md"

authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies]
# Async runtime
tokio = { workspace = true, features = ["macros", "time"] }
futures-util = { workspace = true, features = [] }
async-trait = { workspace = true, features = [] }

# Macros and utilities
thiserror = { workspace = true, features = [] }
derive_more = { workspace = true, features = ["from", "into"] }

# Observability
tracing = { workspace = true, features = [] }

# (De)serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [] }
base64 = { workspace = true, features = [] }

# Commonly used datatypes
uuid = { workspace = true, features = ["serde", "v4", "v7"] }
jiff = { workspace = true, features = ["serde"] }
bytes = { workspace = true, features = ["serde"] }
